version: "3.9"

services:
  fapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fapi
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ./uploads:/app/uploads
    environment:
      TZ: UTC
    healthcheck:
      # Use healthCheck utility for health probe
      test: ["CMD", "/app/healthCheck", "--host=localhost", "--port=8989", "--check=health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

